Stripeとの商品同期の実装 #6
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #10
Opened 2024-05-07 08:46 UTC by AkinoJoey

## 概要
Stripeダッシュボードで商品を追加または削除すると、Webhookを介してバックエンドを呼び出し、データベース内の商品を同期する機能を実装しました。

### Issue
[【Sprint2】Stripeとの商品同期の実装 #6](https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/issues/6)

## 目的
管理者がStripeダッシュボードから商品を追加、削除できるようにするため

## やったこと
- stripeのセットアップ
- stripe_webhookコントローラーの作成
- productsテーブルの作成
- productモデルの作成
- モデルのバリデーションのテストを作成

## やってないこと
- Stirpe→バックエンドは実装していますが、バックエンド→Stripeは未実装です。つまり、バックエンド側で商品を追加、削除してもStripe側には反映されません

## 確認方法

### コンテナのセットアップ
以下はsrcディレクトリ内で行ってください。

コンテナを立ち上げる
`docker compose up —build -d`

コンテナの中に入る
`docker compose exec app bash`

### webhook受信の準備
以下はコンテナの中で実行してください。

development.keyファイルを作成
`rails credentials:edit --environment development`

config/credentials/development.keyファイルの内容を共有された鍵情報に書き換えます。

以下を実行してstripeのAPIキーが表示されていればOKです。
`rails credentials:show `

以下のコマンドを実行すると、To authenticate with Stripe, please go to: {URL}が出てくるので、URLをクリックしてブラウザで開いて、アクセスを許可します。
`stripe login`

以下のコマンドを実行して、webhookをリッスンします。
`stripe listen --forward-to localhost:3000/stripe/webhook`

### stripeダッシュボードから商品を追加

以下のページに飛んで「商品を追加」をクリック。
名前、説明、金額を入力して商品を追加します。
https://dashboard.stripe.com/test/products?active=true

### データベースを確認
コンテナ内のターミナルに戻って、`ctrl + c`を押して、stripe listenをストップします。

コンソールに入ります。
`rails c`

以下を実行して、先程ダッシュボードで追加した商品が表示されているか確認します。
`Product.all`

商品が追加されていたら `exit`を入力してコンソールを終了します。

### 商品を削除
再度コンテナ内で以下を実行して、リッスンします。
`stripe listen --forward-to localhost:3000/stripe/webhook`

以下のページから先程追加した商品を削除します。
https://dashboard.stripe.com/test/products?active=true

`ctrl + c`でstripe listenを止めます。

再度コンソールに入ります
`rails c`

`Product.all`を実行して、商品が表示されていなければデータベースからも商品が削除されています。

## レビューで見てほしいこと、不安に思っていること
- 商品追加と削除の同期が問題なくできているかどうか

## その他
ステージング環境、本番環境がまだ出来ていないため、このプルリクでは[ローカル環境でのテスト](https://dashboard.stripe.com/test/webhooks/create?endpoint_location=local&events=product.created%2Cproduct.deleted)のみ行っています。
ステージング環境、本番環境が整ったあと、[エンドポイントを登録する](https://docs.stripe.com/webhooks?locale=ja-JP#register-webhook)予定です。

2024-05-08 07:27 UTC, Aki158 commented
実装ありがとうございます！
細かく、プッシュされているので、何を変更されているのかわかりやすくて良いですね👍
僕の環境で、**商品追加と削除の同期が問題なくできている**こと確認できました。
基本的には、問題ないですが、コードに対して2箇所レビューコメントを入れました。
また、昨日のミーティングで説明されていた際に気づかれていた「日本時間の現在時刻との日時のずれ」も一緒に、修正してもらえると嬉しいです。

```
created_at: Wed, 08 May 2024 06:50:27.940129000 UTC +00:00,
updated_at: Wed, 08 May 2024 06:50:29.734489000 UTC +00:00,
```

2024-05-08 08:28 UTC, Aki158 requested changes

2024-05-08 09:08 UTC, AkinoJoey commented
@Aki158 
ご確認ありがとうございます！
以下3点修正完了しました！

- priceバリデーションにint型の型指定を追加
- テスト用データのpriceの型を修正
- タイムゾーンを修正

2024-05-08 14:33 UTC, Aki158 commented
@AkinoJoey 

修正ありがとうございます！

後出しで申し訳ないですが、1点気になったので質問させてください。

## 疑問点

`src/app/models/product.rb`でname,price,descriptionを定義されていますが、Akinojoyさんとしては、以下のような項目についてどのように考えてますか?
僕が実装するなら、商品追加時に、以下に対応するバリデーションを設定した方が良さそうだなーと思いました。
正解はないと思うので、「商品の追加時は、あえてバリデーションを厳しくせず、商品情報の更新時に、バリデーションをしっかり設定する」のような意見であれば、今回の実装で良さそうな気がしています。

- 商品名の重複
- 商品名の最大文字数
- 商品説明の最大文字数
- etc...

## 参考

[Active Record バリデーション](https://railsguides.jp/active_record_validations.html)

2024-05-09 01:54 UTC, AkinoJoey commented
@Aki158 
ご指摘の通りname,price,descriptionの厳重なバリデーションは必要かと思いますし、その内容は3人で話し合って決めるべきポイントかと思います！

ただ、今回のプルリクは「Stripeとの商品同期の実装」が主な目的ですので、バリデーションに関しては基本的な実装のみ行いました！

2024-05-09 02:19 UTC, Aki158 approved these changes

2024-05-09 02:25 UTC, Aki158 commented
@AkinoJoey 

話し合って決めるのが良さそうですね。
目的理解しました。
バリデーションは、後からでも追加できると思うので、とりあえず問題なさそうですね。

今回の僕のレビューは以上になります。
承認しておきました。

seiさんがレビューされなければ、僕のレビューでOK出たということでマージしてもらって良いと思います！

2024-05-09 02:33 UTC, AkinoJoey commented
@Aki158 
レビューありがとうございました！
Productのバリデーションに関するイシュー作成しておきます！

マージします！！

2024-05-09 02:34 UTC, merged