Feature/#5 create auth admin
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #11
Opened 2024-05-08 13:51 UTC by seiichikick0404

## 関連するIssueやプルリクエスト
#5 

## 変更の概要
- 認証機能の実装

## なぜこの変更をするのか

管理者が安全にダッシュボードにログインする

## やったこと
- ユーザー新規登録
- ログイン機能の実装
- ログアウト機能の実装
- アドレス確認メールの再送信
- パスワードリセット
- ログイン状態の永続化(2週間)
- ローカル用のメールサーバーの準備

## どうやるのか
### 新規登録
フォームに必要事項を入力し、新規登録。</br>
<img width="513" alt="スクリーンショット 2024-05-08 22 12 35" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/0512c914-45ba-44ad-bf29-db0bea629a8a">

http://localhost:8025/ にアクセスしてアドレス確認メールが届いてるか確認</br>
<img width="1713" alt="スクリーンショット 2024-05-08 22 27 48" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/28e3aaad-bded-43f5-92a0-00734950b5cb">

確認用のリンクにアクセスして/sampleに遷移できればOK</br>
※現状は/sampleをdashboardとして実装してます。</br>

/sampleページで画面右上のログアウトボタンを押すことでログアウト可能です。</br>

### ログイン
<img width="476" alt="スクリーンショット 2024-05-08 22 19 26" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/2bf4665b-29a3-4ba8-ae36-5ff062bb8426">

必要事項を入力してログインボタンを押すと/sampleに遷移します。</br>
ログイン状態で認証ページにアクセスしても/sampleに戻されるようにしてます。</br>

### パスワード再発行
<img width="458" alt="スクリーンショット 2024-05-08 22 14 12" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/cc68b79d-b871-47cc-9862-4669e31b2756">

ログインフォーム下部の「パスワードを忘れた方」というリンクから再設定するためのメール送信フォームに遷移します</br>
ここでメールアドレスを入力し、送信すると再設定用のメールが届きます。

<img width="1234" alt="スクリーンショット 2024-05-08 22 39 30" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/3b7c7417-eb9f-40cb-951a-f0137df14afb">

上記の確認リンクから再設定用のリンクへ進み、パスワードの変更が可能です。

## その他変更した設定
- セッション保持時間120分
- remenber meは2週間に設定 -> remenber meを有効化した場合、2週間が経過するとセッション切れになる
- バリデーションやメールの送信完了等の通知はフラッシュメッセージで出力してます。
- フォーム下部のリンク群はdevise推奨の表示にしてます。(変更可)

## とくにレビューしてほしいところ
基本的な認証機能が正常に動作するか</br>
- ログイン・ログアウトは正常に動作するか
- 基本的なバリデーションは機能してるか
- フラッシュメッセージは問題なく表示されてるか
- 認証メール等は正常に送信されるか
- 認証周りの導線は問題ないか

## 備考

* その他に伝えたいこと

2024-05-09 10:25 UTC, AkinoJoey requested changes
基本的な認証機能の部分は問題なく動作しました！ありがとうございます！
1点、インラインコメントに残したadmin_account_relationshipsの部分、ご確認お願い致します！

2024-05-09 10:25 UTC, AkinoJoey commented on src/db/migrate/20240503014119_create_admin_account_relationships.rb
Adminテーブルとモデルを作成して、admin_acccountとaddressに対して[has_oneの関連付け](https://railsguides.jp/association_basics.html#has-one%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91)を行ったほうが、シンプルな設計になると思いますが、どうでしょうか？？

また、関連付けしておけば、Adminからaccountとaddressの情報を取れるようになるので、後々便利かと思います！

2024-05-10 09:17 UTC, Aki158 commented
@seiichikick0404 

プルリクありがとうございます！
僕がデザインしたものより、良くなっている気がします〜

僕のローカル環境で**基本的な認証機能が正常に動作する**こと確認できました。
(コード見た感じ、device便利そうですね!)

また、パスワードの文字列に対するバリデーションについて、1件コメントしました。
お手数ですが、対応お願いします🙇

2024-05-10 09:18 UTC, Aki158 requested changes
@seiichikick0404 

プルリクありがとうございます！
僕がデザインしたものより、良くなっている気がします〜

僕のローカル環境で**基本的な認証機能が正常に動作する**こと確認できました。
(コード見た感じ、device便利そうですね!)

また、パスワードの文字列に対するバリデーションについて、1件コメントしました。
お手数ですが、対応お願いします🙇

2024-05-10 09:18 UTC, Aki158 commented on src/spec/factories/admin_accounts.rb
> +    password_confirmation { 'password123' }
アカウント作成とログインの入力フォームには、「半角英数記号8文字以上」という記載がありますが、テストの入力として満たしていない気がします。
(記号とか面倒であれば「半角英数8文字以上」とかに変更してもらってOKです)

また、deviseの設定として`src/config/initializers/devise.rb`を確認しましたが、パスワードのバリデーションは、文字列の長さしか設定されていないように見えました。
以下の対応をお願いします。

## やってほしいこと
- パスワードの文字列に対するバリデーションの処理追加
- テストの入力修正(`password`と`password_confirmation`)

2024-05-10 23:57 UTC, AkinoJoey requested changes
Rubocopの設定について追記しました！

2024-05-10 23:57 UTC, AkinoJoey commented on src/.rubocop.yml
Layout/LineLength、Metrics/MethodLengthは冗長性を防いで、読みやすいコードにするためにもfalseではなく数値を設定したほうが良いと思いました！
例えばLayout/LineLengthは160, Metrics/MethodLengthは20ぐらいが個人的には良いかな、と思います。

Naming/VariableNumberも数字の書き方を統一するためにもfalseじゃないほうが良いかと思いました！

2024-05-11 05:31 UTC, AkinoJoey approved these changes
問題ないです！修正ありがとうございました！

2024-05-11 16:15 UTC, Aki158 approved these changes
修正されていること確認できました!
マージしてもらってOKです。
おつかれさまでした🙇

2024-05-11 23:39 UTC, merged