Feature/#91 chat list[まだレビュー不要]
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #122
Opened 2024-07-07 01:29 UTC by seiichikick0404

## 概要
チャットリストのステータス変更

## 目的

複数オペレーターがチャットの状態をリアルタイムで確認しながらチャット対応できるようにする

## やったこと

- action cableの導入
- 管理者がチャットリストに参加すると「対応中」に変更
- 接続が切れた際に相手の接続も解除してチャットリストに反映
- 画面遷移すると接続が解除させる(相手のwebsocketも解除)

## やってないこと
- 特になし

## 確認方法
### チャットへの参加確認
1. 顧客アカウントでチャットにアクセス
2. 管理者アカウントで複数タブを開き(リストの変更を確認するため)チャットリストにアクセス
3. チャットに接続したらチャットリストのステータスが「対応中」に変更されたらOK

### 接続解除の確認方法
1. チャットへの参加は上記と同様
2. 管理者もしくは顧客側で「接続解除」ボタンを押したらチャットリストから削除される
3. 解除された側にもアラートが表示されてればOK
4. 画面遷移時も同様の挙動が確認できればOK

README.mdを一読する

## レビューで見てほしいこと、不安に思っていること

- ステータス変更時にリアルタイムで反映されるか
- 管理者参加時に対応中ステータスに問題なく切り替わるか
- 接続解除ボタンは問題なく動作するか
- 画面遷移をすると接続は解除されるか
- 片方の通信が解除されたらもう片方も通信が解除されるか

## その他

2024-07-11 08:43 UTC, Aki158 requested changes
実装ありがとうございます！
ステージング環境で以下問題ないこと確認できました。
- ステータス変更時にリアルタイムで反映されるか
- 管理者参加時に対応中ステータスに問題なく切り替わるか
- 接続解除ボタンは問題なく動作するか
- 画面遷移をすると接続は解除されるか
- 片方の通信が解除されたらもう片方も通信が解除されるか

レビューコメントを記載したので、対応お願いします。
(主にチャットページの指摘なので、別のissueで対応するのも有りな気がしています。)

## レビュー
- 管理者側のチャットページについて
通常のチャットだと、相手の名前が表示されると思うので
「カスタマーサポート」には、Eメールを表示するように変更した方がいいと思います。

- 「接続解除」ボタンをクリックすると、すぐに解除されるので「確認ダイアログ」にした方がいい気がします。(重要なので赤いボタンにされてる認識です！)

- 接続解除後も送信ボタンがクリックできるので、メッセージを送信できないようにした方がいいと思いました。

- 入力フォームにメッセージを未入力の状態でも送信が出来てしまいます。未入力やスペースのみなどの入力時は、送信できないようにした方がいいと思います。

- 画像ボタンがクリックしても反応しません。

- リアルタイム通信は、ユーザーとカスタマーサポートの両方がチャットページを開く必要がある認識です。現状の挙動だと、ユーザーが以下のような行動をしても、カスタマーサポートにメッセージが届かないので、初回のチャットでそのことを伝えるなどの工夫が必要な気がします。
  例えば、ユーザーがチャットページにアクセス後は、「カスタマーサポートの担当者が対応します。しばらくお待ちください。※カスタマーサポートから次のメッセージが表示されるまでは、メッセージを送信してもカスタマーサポートには、表示されませんのでご注意ください。」とチャットで表示する。<br>
ユーザーがチャットページを開く<br>
↓<br>
「こんにちは」と入力してメッセージを送信する<br>
↓<br>
ユーザー側のチャットページ : 「こんにちは」が表示される<br>
カスタマーサポート側のチャットページ : 管理者は、チャットを開いていないので、「こんにちは」が表示されない。。。

2024-07-13 01:55 UTC, seiichikick0404 commented
> * 管理者側のチャットページについて
>   通常のチャットだと、相手の名前が表示されると思うので
>   「カスタマーサポート」には、Eメールを表示するように変更した方がいいと思います。
> * 「接続解除」ボタンをクリックすると、すぐに解除されるので「確認ダイアログ」にした方がいい気がします。(重要なので赤いボタンにされてる認識です！)
> * 接続解除後も送信ボタンがクリックできるので、メッセージを送信できないようにした方がいいと思いました。
> * 入力フォームにメッセージを未入力の状態でも送信が出来てしまいます。未入力やスペースのみなどの入力時は、送信できないようにした方がいいと思います。
> * 画像ボタンがクリックしても反応しません。
> * リアルタイム通信は、ユーザーとカスタマーサポートの両方がチャットページを開く必要がある認識です。現状の挙動だ

以下対応しました。

- 管理者側にユーザーのメールアドレスを表示
- 「接続解除ボタン」を確認ダイヤログを表示するよう変更
- 未入力やスペースのみのメッセージ送信を無効化
- 初回メッセージで管理者からのメッセージが来るまでメッセージが表示されない旨を通知する

**未対応**
画像送信については未実装なので別のイシューで対応します

2024-07-13 12:31 UTC, Aki158 approved these changes
修正ありがとうございます！
使いやすくなった気がします。
承認しておきました〜

2024-07-15 00:24 UTC, seiichikick0404 commented
> 修正ありがとうございます！ 使いやすくなった気がします。 承認しておきました〜

マージしちゃいますね！

2024-07-15 00:26 UTC, merged