【Sprint2】商品の基本管理機能の実装（編集、削除、 Stripeとの同期含む） #7
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #21
Opened 2024-05-13 14:01 UTC by AkinoJoey

## 概要
Eコマースアプリの管理者用ページにおける、商品の編集・削除の機能を実装しました。
管理者用ページで行った編集、削除の内容はStripeダッシュボードに反映されます。

### Issue
[【Sprint2】商品の基本管理機能の実装（編集、削除、 Stripeとの同期含む） #7](https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/issues/7)

## 目的
管理者がEコマースアプリの専用ページから商品を編集、削除できるようにするため

## やったこと
- admin/productsコントローラの作成
- 各ビュー、アクションの作成
- stripe cli用のコンテナのセットアップ
- ProductCategoryモデルの作成

## やってないこと
- 画像アップロードの実装
- 商品フィルタリングの実装
- 管理者ダッシュボードでの商品の追加機能
- Stripeで商品を編集→Eコマース管理ページへの反映
- StripeダッシュボードとEコマースアプリとの完全な同期（例えばStripeダッシュボードでメタデータの入力を忘れると、エラーが発生してバックエンド側では商品は作成されません。Stripeダッシュボードに商品はあるが、Eコマースアプリのダッシュボードには商品はない。という状態が発生します）

## 確認方法
### 環境変数の追加
src/.envに以下の2つを追加してください。

- STRIPE_API_KEY
- STRIPE_DEVICE_NAME

STRIPE_API_KEYは以下のシークレットキーの値を入力。
https://dashboard.stripe.com/test/apikeys

STRIPE_DEVICE_NAMEは適当に自分のニックネームなどで大丈夫です・

### コンテナを立ち上げる
もしsrc/config/credentials/development.keyがない場合は、以下を実行して、共有されたdevelopment.keyを入力してください
`rails credentials:edit --environment development`

コンテナを立ち上げる
`docker compose —build -d`

### 商品を追加する
http://localhost:3000/admin/products を開く。これが商品一覧を閲覧できるページです。

https://dashboard.stripe.com/test/products?active=true にアクセスして以下の項目に適当な値を入力して商品を追加してください。

- 名前
- 説明
- その他のオプション > メタデータ を開いて、キーにproduct_category, 値に「絵画、彫刻、写真、イラスト」のいずれか。
- 金額

ちなみに、商品を追加した後、Docker Desktopでapp-1のLogsを見ると、ステータスコードや実行されているクエリなどを確認できます。

http://localhost:3000/admin/products を更新すると、商品が追加されています。

### 商品を編集する
http://localhost:3000/admin/products にある「編集」をクリックすると、各商品の編集画面に飛べます。

以下を編集して、保存してみてください
- 名前
- 説明
- カテゴリー
- 金額

https://dashboard.stripe.com/test/products?active=true を開いて、先程追加した商品詳細画面を開きます。
商品が編集されているのを確認してください。

### 商品を削除
http://localhost:3000/admin/products の「削除」をクリックして、アラートのOKをクリック

https://dashboard.stripe.com/test/products?active=true を開いて、商品がアーカイブ済みになっているのを確認してください。

## レビューで見てほしいこと、不安に思っていること
- 管理者ダッシュボードでの編集、削除実行時のStripeとの同期が問題なくできているかどうか

## その他
- Stripe APIからは価格が付いている商品を削除はできないため、[アーカイブ済み](https://docs.stripe.com/products-prices/manage-prices?locale=ja-JP&dashboard-or-api=api#archive-product)にするという仕様のようです。
そのため、今回の実装では厳密には商品は削除されるのではなく、アーカイブされます。

- 今回のプルリクはEコマース専用ページの編集→Stripeダッシュボードへの反映なので、Stripeダッシュボードでの編集→Eコマース専用ページへの反映は実装していません。

2024-05-14 13:11 UTC, seiichikick0404 commented
akinoさん指定の手順で確認するとコンテナ起動時にエラーが発生したので共有したいと思います。
### 発生中のエラー
```
ActiveSupport::MessageEncryptor::InvalidMessage
```

###
STRIPE_API_KEYとSTRIPE_DEVICE_NAMEはセットしてます。
以下を実行してコンテナをビルドするとエラーが発生してる状況です
> rails credentials:edit --environment development

development.keyは作成されているので暗号の復号周りで失敗しちゃってるんですが何か分かりますかね？🤔
master.keyの値が私が使ってるのと違う？のかも...

2024-05-14 13:36 UTC, seiichikick0404 commented
Stripe側に商品を追加したのですが、商品管理に反映されないので一度確認お願いできますか？
ログを見るとwebhookは動いてるっぽいのですがなんらかの理由でDB側に保存されてないみたいです。
```bash
app-1     | 22:29:16 web.1  | Started POST "/stripe/webhook" for 172.26.0.1 at 2024-05-14 22:29:16 +0900
app-1     | 22:29:16 web.1  | Cannot render console from 172.26.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
app-1     | 22:29:16 web.1  | Processing by StripeWebhooksController#handler as XML
app-1     | 22:29:16 web.1  |   Parameters: {"id"=>"evt_1PGLPr2KrybDMqMJmkO2GUkQ", "object"=>"event", "api_version"=>"2024-04-10", "created"=>1715693355, "data"=>{"object"=>{"id"=>"prod_Q6YQsL0lDXA8Mb", "object"=>"product", "active"=>true, "attributes"=>[], "created"=>1715692943, "default_price"=>"price_1PGLJD2KrybDMqMJGIFteIOm", "description"=>"test1", "images"=>[], "livemode"=>false, "marketing_features"=>[], "metadata"=>{"product_category"=>"イラスト"}, "name"=>"test1", "package_dimensions"=>nil, "shippable"=>nil, "statement_descriptor"=>nil, "tax_code"=>nil, "type"=>"service", "unit_label"=>nil, "updated"=>1715693355, "url"=>nil}, "previous_attributes"=>{"updated"=>1715693354}}, "livemode"=>false, "pending_webhooks"=>2, "request"=>{"id"=>"req_IaTJElp5NeRduJ", "idempotency_key"=>"[FILTERED]"}, "type"=>"product.updated", "stripe_webhook"=>{"id"=>"evt_1PGLPr2KrybDMqMJmkO2GUkQ", "object"=>"event", "api_version"=>"2024-04-10", "created"=>1715693355, "data"=>{"object"=>{"id"=>"prod_Q6YQsL0lDXA8Mb", "object"=>"product", "active"=>true, "attributes"=>[], "created"=>1715692943, "default_price"=>"price_1PGLJD2KrybDMqMJGIFteIOm", "description"=>"test1", "images"=>[], "livemode"=>false, "marketing_features"=>[], "metadata"=>{"product_category"=>"イラスト"}, "name"=>"test1", "package_dimensions"=>nil, "shippable"=>nil, "statement_descriptor"=>nil, "tax_code"=>nil, "type"=>"service", "unit_label"=>nil, "updated"=>1715693355, "url"=>nil}, "previous_attributes"=>{"updated"=>1715693354}}, "livemode"=>false, "pending_webhooks"=>2, "request"=>{"id"=>"req_IaTJElp5NeRduJ", "idempotency_key"=>"[FILTERED]"}, "type"=>"product.updated"}}
app-1     | 22:29:17 web.1  |   Product Load (0.5ms)  SELECT `products`.* FROM `products` WHERE `products`.`stripe_product_id` = 'prod_Q6YQsL0lDXA8Mb' LIMIT 1
app-1     | 22:29:17 web.1  |   ↳ app/controllers/stripe_webhooks_controller.rb:58:in `update_product_price'
app-1     | 22:29:17 web.1  | Completed 200 OK in 1112ms (ActiveRecord: 0.5ms | Allocations: 3785)
```

追加した商品です。登録内容に問題などあれば教えていただきたいです！
<img width="617" alt="スクリーンショット 2024-05-14 22 34 39" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/9b215a19-b634-4693-aab4-b6a3a2cd7bb1">

2024-05-15 02:00 UTC, AkinoJoey commented
@seiichikick0404 
ご確認ありがとうございます！
私のPCでは再現できていないのですが、恐らくstripeコンテナとappコンテナのネットワークのやり取りが上手くいないのが原因かもしれません。

stripeコンテナのcommandオプションを修正して、リッスン先をDockerコンテナ上のホストマシンのIPアドレスに変更しました。
今回の変更で上手くいくかと思います！

2024-05-15 18:24 UTC, Aki158 requested changes
実装ありがとうございます！
seiさんがコメントされていた商品管理に反映されない問題について
僕の環境では、問題なく動きました！
基本的に問題なさそうですが、以下気になりました。

### レビュー
ECサイトの商品情報の編集ページで、価格を変更して保存すると、変更前の金額が表示されます。
(何度か試すと、再現できるかと思います)
例えば、140→146に変更して保存ボタンをクリックすると、140に戻ります。

2024-05-16 03:11 UTC, AkinoJoey commented
@Aki158 
ご確認ありがとうございます！
僕のほうでも、変更前の金額が表示された挙動が確認できました。

おそらくキャッシュが原因と思うので、リダイレクト前にキャッシュを無効化する挙動を追加しました。
これで修正できたかと思います！

```rb
  # 更新前のデータが表示される場合があるのでキャッシュを無効化する
      expires_now

      redirect_to edit_admin_product_path @product
```

2024-05-16 05:37 UTC, Aki158 approved these changes
修正ありがとうございます！
問題ないこと確認できました。
僕のレビューは以上になります。
お疲れ様でした🙇

2024-05-16 12:25 UTC, seiichikick0404 commented
> @seiichikick0404 ご確認ありがとうございます！ 私のPCでは再現できていないのですが、恐らくstripeコンテナとappコンテナのネットワークのやり取りが上手くいないのが原因かもしれません。
> 
> stripeコンテナのcommandオプションを修正して、リッスン先をDockerコンテナ上のホストマシンのIPアドレスに変更しました。 今回の変更で上手くいくかと思います！

私の方も問題なく動くようになってました！
今回未対応の下記の項目などは忘れないうちにイシューに入れてもらえればと思います👍
- エラー時の商品の同期
- ダッシュボード側からの商品追加
- その他あれば

お疲れ様でした！

2024-05-16 12:26 UTC, seiichikick0404 approved these changes

2024-05-17 03:39 UTC, merged