Feature/#17 create wish list
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #30
Opened 2024-05-21 00:59 UTC by seiichikick0404

## 概要
ウィッシュリストの作成

### Issue
#17

## 目的
ユーザーがウィッシュリストの作成をして購入のサポートをする

## やったこと
- 顧客アカウント作成時にaddressとcustomerを作成
- ウィッシュリストのデザイン変更
- ウィッシュリストへの追加
- ウィッシュリストからの削除
- リンクの共有機能

## やっていないこと
- ページネーション
- 存在しないcustomer_idを指定した際のエラーハンドリング

## 事前準備
- 商品を最低1件は登録する
- 顧客アカウントでログイン
-
※ログイン中でないとウィッシュリストへのアクセスはできません

## 確認方法
### 1.ウィッシュリストへ追加
http://localhost:3000/products/product_id
上記にアクセスして「ウィッシュリストに追加する」をクリックすると追加されます。
※product_idの部分は既に登録されてるproduct_idを入力して下さい。

### 2.ウィッシュリストの一覧を確認する
<img width="183" alt="スクリーンショット 2024-05-21 9 42 41" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/aa65d252-c8bf-48f7-a2ed-e43b7a2dee54">

ヘッダーのメニューバーからウィッシュリストを選択すると自分のウィッシュリストへアクセスできます。

### 3.ウィッシュリストから削除する
ウィッシュリスト > 「削除する」を選択するとウィッシュリストから削除できます

## レビューで見てほしいこと、不安に思っていること
- ウィッシュリストが機能要件を満たしているかどうか
- ログイン状態のみウィッシュリストに

## その他
リンクのコピーはjsで実装してるので、rails assets:precompileを行ってからdocker composeで再起動しないと反映されないかもしれません。
TSのホットリロードが効かないので方法がわかる方いたら教えて頂けると助かります🙇‍♂️
sample.tsが効いてるのでどこかで読み込ませる設定が必要なのかも...

2024-05-21 08:44 UTC, AkinoJoey requested changes
実装ありがとうございます！
正常に作動したので、動作的には問題ありません。
いくつかコメントしたので確認お願いします！

私の環境では、```rails assets:precompil```をしなくても問題なく動きました！
TSのホットリロードが効かない件に関してですが、おそらくセイさんの環境では[こちらのような環境](https://qiita.com/GandT/items/4b3701a6ca51ff84370c#%E5%8E%9F%E5%9B%A0)になっていると思うので、```rails assets:precompile``` で生成されたassetsを削除すればホットリロードされるかもしれません！

2024-05-21 08:44 UTC, AkinoJoey commented on src/spec/requests/wish_products_spec.rb
こちら必要なさそうなので削除お願いします！

2024-05-21 08:44 UTC, AkinoJoey commented on src/spec/models/customer_spec.rb
こちら簡単でも良いので実装お願いします！

2024-05-21 08:44 UTC, AkinoJoey commented on src/spec/helpers/wish_products_helper_spec.rb
こちら不要そうなので削除お願いします！

2024-05-21 08:44 UTC, AkinoJoey commented on src/app/views/customer/wish_products/index.html.erb
- 「リンクの共有」はページ遷移じゃないので、aタグじゃなくてbuttonタグが適切かと思います！
- 自分以外のウィッシュリストを閲覧しているときも「リンクの共有」ボタンが押せちゃうので修正お願いします！
- リンクの共有ボタンを押した時に作成されるリンクが、/customer_accounts/{user_id}/wish_productsだと、簡単に予測できちゃうリンクになるので、/wish_products/{random_string}みたいな感じが良いと思いますが、どうでしょうか？

2024-05-22 09:01 UTC, Aki158 approved these changes
PRありがとうございます！
僕のローカル環境で問題なく動くこと確認できました。

僕からの指摘はありませんので、AkinoJoeyさんのレビューコメントに対応されたらマージお願いします。
お疲れ様でした🙇

2024-05-22 10:10 UTC, seiichikick0404 commented
> PRありがとうございます！ 僕のローカル環境で問題なく動くこと確認できました。
> 
> 僕からの指摘はありませんので、AkinoJoeyさんのレビューコメントに対応されたらマージお願いします。 お疲れ様でした🙇

確認ありがとうございます！

2024-05-22 14:12 UTC, seiichikick0404 commented on src/app/models/address.rb
addressのアソシエーション対応は完了しました。
Customerのカラム変更は別ブランチで対応します！

2024-05-22 14:14 UTC, seiichikick0404 commented on src/app/models/customer_account.rb
customer_accountのみアソシエーションの方向が逆になってますが、後で対応します。

2024-05-22 14:14 UTC, seiichikick0404 commented on src/config/routes/customer_routes.rb
Lintの設定でroutes.rbを外して対応しました！

2024-05-22 14:15 UTC, seiichikick0404 commented on src/spec/requests/wish_products_spec.rb
削除済みです！

2024-05-22 14:15 UTC, seiichikick0404 commented on src/spec/helpers/wish_products_helper_spec.rb
削除済みです！

2024-05-22 14:16 UTC, seiichikick0404 commented on src/app/views/customer/wish_products/index.html.erb
リンクの共有ページの表示処理は対応済みです！
URLについて別イシューで対応します！

2024-05-23 02:52 UTC, AkinoJoey approved these changes
@seiichikick0404 
修正ありがとうございました！
問題ありません！お疲れ様でした！

2024-05-23 09:16 UTC, merged