Feature/#18 favorite page
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #32
Opened 2024-05-25 08:20 UTC by seiichikick0404

## 概要
お気に入りリストの作成

### Issue
#18 

## 目的
ユーザーがお気に入りリストを作成をして購入のサポートをする

## やったこと
- お気に入りの追加
- お気に入りリストから削除
- テーブル構成の変更

## やっていないこと
- ページネーション

## 事前準備
- 商品を最低1件は登録する
- 顧客アカウントでログイン
-
※ログイン中でないとお気に入りリストへのアクセスはできません

## 確認方法
### 1.お気に入りリストへ追加
http://localhost:3000/products/product_id
上記にアクセスして「お気に入りリストに追加する」をクリックすると追加されます。
※product_idの部分は既に登録されてるproduct_idを入力して下さい。

### 2.お気に入りリストの一覧を確認する
<img width="183" alt="スクリーンショット 2024-05-21 9 42 41" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/aa65d252-c8bf-48f7-a2ed-e43b7a2dee54">

ヘッダーのメニューバーから「お気に入り」を選択するとことでアクセスできます。

### 3.お気に入りリストから削除する
お気に入りリスト > 「削除する」を選択するとお気に入りリストから削除できます

## レビューで見てほしいこと、不安に思っていること
- お気に入りリストが機能要件を満たしているかどうか
- ログイン中ユーザーのお気に入りリストがちゃんと表示されるか

## その他
基本的な動きはお気に入りリストの時と同じです。
以前のMTGでも話したようにテーブルの構造を修正してます。
customersテーブルはカラムを持たずにrailsのアソシエーションで関連付けされてます。
その代わり、customersテーブルとcustomer_accountsテーブルの両方にcustomer_idを追加して参照できるようにしてます

2024-05-25 22:51 UTC, AkinoJoey approved these changes
実装ありがとうございます！
問題なく動作しました！

ただ、同じページを2つ開いて、1つのページで「お気に入りリストに追加する」ボタンを押した後、更新しないまま別のページで「お気に入りリストに追加する」ボタンを押すと、エラーが起きるのでエラーハンドリングが必要かもです！

時間がかかりそうだったら飛ばして大丈夫です！

2024-05-25 23:50 UTC, seiichikick0404 commented
> 実装ありがとうございます！ 問題なく動作しました！
> 
> ただ、同じページを2つ開いて、1つのページで「お気に入りリストに追加する」ボタンを押した後、更新しないまま別のページで「お気に入りリストに追加する」ボタンを押すと、エラーが起きるのでエラーハンドリングが必要かもです！
> 
> 時間がかかりそうだったら飛ばして大丈夫です！

確認ありがとうございます！
確かにそのパターンは盲点でした😳
メモして後々修正しようと思います。

2024-05-26 01:30 UTC, Aki158 requested changes
実装ありがとうございます！
僕のローカル環境で問題なく動作すること確認できました。
機能要件も満たされていると思います。

1件、レビューコメントしたので対応お願いします。

2024-05-26 01:30 UTC, Aki158 commented on src/app/views/customer/products/show.html.erb
> +                  <%= favorite_button(@product, current_customer_account) %>
ゲストユーザーの場合、「お気に入りに追加する」などのオプションボタンがなく、メッセージだけになっています。

このコードについての直接的な指摘ではないですが、`<% if current_customer_account %>`と`<% end %>`で囲まれている範囲を以下のように修正して「購入を検討しているユーザーへのオプション」を非表示にした方がよいかと思いました。

```
    <!-- 購入を検討しているユーザーへのオプション -->
    <% if current_customer_account %>
        <div class="w-full py-4 md:w-3/4">
            <div class="flex flex-col space-y-4">
                <h2 class="pl-12 text-sm md:pl-6 md:text-lg">
                    購入するか迷われていますか?<br />
                    以下の機能を利用してさらに情報を集めてみましょう。
                </h2>
                <div class="flex flex-col items-center md:flex-row">
                    <%= wishlist_button(@product, current_customer_account) %>
                    <%= favorite_button(@product, current_customer_account) %>
                    <button type="button" class="my-2 rounded-xl border border-gray-300 bg-white px-6 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700 md:mx-6 md:w-1/3">
                        商品についてチャットする
                    </button>
                </div>
            </div>
        </div>
    <% end %>
```

2024-05-26 07:52 UTC, seiichikick0404 commented on src/app/views/customer/products/show.html.erb
> +                  <%= favorite_button(@product, current_customer_account) %>
ツールバーの表示で対応してみました。どうでしょう？

2024-05-26 08:47 UTC, Aki158 commented on src/app/views/customer/products/show.html.erb
> +                  <%= favorite_button(@product, current_customer_account) %>
いいと思います！

2024-05-26 09:37 UTC, merged