Feature/#34 tracking number
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #51
Opened 2024-06-02 10:19 UTC by AkinoJoey

## 概要
- 管理者が使用できる発送管理ページの実装
- 管理者が追跡番号を入力すると発送通知のメールが顧客に送られる機能の実装

### Issue
[https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/issues/34](https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/issues/34)

## 目的
管理者が発送管理をできるようにするため
顧客がリアルタイムで発送状況を確認できるようにするため

## やったこと
- Shipping modelの作成
- バリデーションの作成
- テストケースの作成
- create_shipping関数の作成
- Shippings Controllerの作成
- index,showのフロントエンドの作成
- index, showを実装
- NotificationMailerの作成
- NotificationPreviewの作成
- [ER図](https://github.com/recursion-backend-projects/dev-log/blob/main/er.md)の修正(Shippingテーブルの追加)

## やっていないこと
- 発送管理ページのフィルター機能の実装
- 注文後すぐに自動送信メール配信の実装

## 確認方法
1.物理製品を含む商品を最低限1つ以上カートに入れて決済する
2.発送管理ページ（ http://localhost:3000/admin/shippings ）で、購入された商品がステータス「未発送」状態で追加されていることを確認する
![Screenshot 2024-06-02 at 18 50 08](https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/124570638/f0cf3977-3fb8-41b3-9282-af44cc1065c4)

3.発送管理ページで「追跡番号の入力」を押して、配送会社と追跡番号を入力して「発送通知を送る」を押す
4.発送管理ページに戻って、ステータスが「発送済み」になっていることを確認する
5.http://localhost:8025/ で発送通知メールが送信されていることを確認する

1度発送通知を送った後は、下記の画像のようにformはグレーアウトして、disabledになって送信できないようにしています。
![Screenshot 2024-06-02 at 18 28 16](https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/124570638/b648db87-5346-4dfc-b686-37ddef4f8c98)

## レビューで見てほしいこと、不安に思っていること
- 物理製品を購入したときに発送管理ページに追加されているか
- 発送通知メールが送られているかどうか
- 1度発送通知を送った後に再編集はできないようになっているか

## その他
- [ER図](https://github.com/recursion-backend-projects/dev-log/blob/main/er.md)にShippingテーブルを追加しています

2024-06-02 12:48 UTC, Aki158 commented on src/app/views/admin/shippings/edit.html.erb
> +                    <%= form.select :carrier, Shipping.carriers.keys.map{|key|[I18n.t("shipping.carriers.#{key}"), key]}, { prompt: "選択してください"  }, { required: true,class: 'block rounded-lg border bor
promptオプションを設定するのは、いいと思うのですが、他の入力フォーム(アカウント作成、ログイン、レビュー記入など)では、現状、入力必須の項目にpromptオプションを設定していません。
promptオプションの使用有無をどちらかに統一する方がいいと思いました。
機能的には、問題ないのでissueを作成して後で対応する形でもOKです。

2024-06-02 12:48 UTC, Aki158 commented on src/app/controllers/admin/shippings_controller.rb
> +    @shippings = Shipping.all
古い商品が上位に表示される状態になっています。
新しい順に変更した方が、発送漏れしずらい気がしました。

2024-06-02 13:05 UTC, Aki158 commented on src/app/views/admin/shippings/index.html.erb
> +                                <dt class="text-base font-medium text-gray-500 dark:text-gray-400">注文 ID:</dt>
購入履歴ページの`注文番号`と同じ値を使用していると思われます。
`注文番号`か`注文 ID`どちらかに統一してください。

2024-06-02 13:10 UTC, Aki158 commented on src/app/views/customer/carts/show.html.erb
> +                                    <p class="text-sm lg:text-base"><%= I18n.t("products.product_type.#{cart_item.product_type}") + "製品" %></p>
- 他のページでは、`商品`という言葉を使用していた認識です。<br>特に理由がなければ、`商品`に修正してください。
- `<!-- TODO: デジタル、物理のテーブルを作成した時に実装する -->`<br>これは、今回の変更とは、別で対応が必要ですか?<br>対応不要の場合は、削除お願います。

2024-06-02 13:16 UTC, Aki158 requested changes
実装ありがとうございます！
物理製品の発送管理が問題ないこと確認できました。

細かい内容ですが、レビューコメントを入れました。
対応お願いします🙇

2024-06-03 02:06 UTC, AkinoJoey commented on src/app/views/admin/shippings/edit.html.erb
> +                    <%= form.select :carrier, Shipping.carriers.keys.map{|key|[I18n.t("shipping.carriers.#{key}"), key]}, { prompt: "選択してください"  }, { required: true,class: 'block rounded-lg border bor
統一するために promptを削除しました！

2024-06-03 02:06 UTC, AkinoJoey commented on src/app/views/admin/shippings/index.html.erb
> +                                <dt class="text-base font-medium text-gray-500 dark:text-gray-400">注文 ID:</dt>
注文番号に修正しました！

2024-06-03 02:06 UTC, AkinoJoey commented on src/app/views/customer/carts/show.html.erb
> +                                    <p class="text-sm lg:text-base"><%= I18n.t("products.product_type.#{cart_item.product_type}") + "製品" %></p>
- 商品という言葉に修正しました
- 不要なコメントアウトを削除しました

2024-06-03 02:09 UTC, AkinoJoey commented on src/app/controllers/admin/shippings_controller.rb
> +    @shippings = Shipping.all
修正しました！

2024-06-03 11:38 UTC, Aki158 commented on src/app/views/admin/shippings/index.html.erb
> +                                <dt class="text-base font-medium text-gray-500 dark:text-gray-400">注文 ID:</dt>
実装ありがとうございます！
修正されていること確認できました。

2024-06-03 11:40 UTC, Aki158 commented on src/app/views/customer/carts/show.html.erb
> +                                    <p class="text-sm lg:text-base"><%= I18n.t("products.product_type.#{cart_item.product_type}") + "製品" %></p>
実装ありがとうございます！
修正されていること確認できました。

2024-06-03 11:50 UTC, Aki158 commented on src/app/controllers/admin/shippings_controller.rb
> +    @shippings = Shipping.all
実装ありがとうございます！
修正されていること確認できました。

2024-06-03 12:25 UTC, Aki158 commented on src/app/views/admin/shippings/edit.html.erb
> +                    <%= form.select :carrier, Shipping.carriers.keys.map{|key|[I18n.t("shipping.carriers.#{key}"), key]}, { prompt: "選択してください"  }, { required: true,class: 'block rounded-lg border bor
ミーティングでお話しした通り、僕の指摘がまちがっていました🙇

2024-06-03 13:03 UTC, seiichikick0404 commented
実装ありがとうございます！
発送処理問題なく動きました！
ただなぜかこの画面だけ表示崩れちゃうんですよね🤔
フォームとかは問題なく表示されてます！

<img width="742" alt="スクリーンショット 2024-06-03 20 32 32" src="https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/69625901/477e0824-55e1-4da2-9dd9-4892b7a72c76">

2024-06-03 13:12 UTC, seiichikick0404 approved these changes

2024-06-03 13:13 UTC, merged