Feature/#42 edit account
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #54
Opened 2024-06-05 10:48 UTC by AkinoJoey

## 概要
- ログインユーザーがアカウント情報を編集できる機能の実装
- 住所を入力した場合、決済時に自動入力される機能の実装

### Issue
https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/issues/42

## 目的
ログインユーザーが住所の入力の手間を省けるようにするため

## やったこと
- customer/accounts controller の作成
- prefectureクラスの作成
- show, editのビューの作成
- show, edit, updateアクションの作成
- バリデーションの作成
- 単体テストの作成
- 決済時に住所を自動入力させる振る舞いの実装
- [ER図](https://github.com/recursion-backend-projects/dev-log/blob/main/er.md)の修正

## やっていないこと
- Eメールの変更の振る舞い（再認証を求めるなど）

## 確認方法

1. ログインする
2. http://localhost:3000/account にアクセス
3. 「編集する」ボタンを押す
4. アカウント情報を入力する
5. 「保存する」ボタンを押す
6. なにか商品をカートに入れて決済画面に行く
7. アカウント情報が自動入力されているか確認する

## レビューで見てほしいこと、不安に思っていること
- アカウント情報の編集、保存、表示ができるか
- 入力した情報が決済時に自動入力されるか

## その他
- [ER図](https://github.com/recursion-backend-projects/dev-log/blob/main/er.md)のaccount tableとcustomer_accountテーブルを修正してます

2024-06-07 11:39 UTC, Aki158 requested changes
実装ありがとうございます！
アカウント情報の編集、保存、表示、決済時の自動入力されていること確認できました。

1. 決済時のカードデータ
アカウント情報ページでは、
`商品ご購入時に、テスト用のカードデータをご用意致します。`
と記載がありますが、決済時のカードデータも、自動入力させた方が良いと思いました。
(今回は、決済のやりとりが発生しないため、自動入力でも問題ない認識です)

2. ログインユーザーのプロフィール画像
前回の全体MTGで`プロフィール画像を更新できるようにするか`質問され、検討中と回答していた認識です。アカウント情報に関係する箇所だと思われます。MTGでどうするか決めておきたいです。

3. レビューコメント
レビューコメントを1件入れました。
対応お願いします。

2024-06-07 12:13 UTC, Aki158 requested changes

2024-06-08 00:37 UTC, seiichikick0404 commented
実装ありがとうございます！
ユーザー情報編集と自動入力確認できました
私の方からは特に指摘等はないです、お疲れ様でした👍

2024-06-08 00:37 UTC, seiichikick0404 approved these changes

2024-06-08 08:54 UTC, AkinoJoey commented on src/app/models/customer_account.rb
> +    validates :shipping_name, length: { maximum: 50 }
修正しました！

2024-06-08 08:56 UTC, AkinoJoey commented
@Aki158 
色々調査して試してみましたが、やはりカード情報の自動入力は無理そうでした！

2024-06-08 09:47 UTC, Aki158 commented on src/app/models/customer_account.rb
> +    validates :shipping_name, length: { maximum: 50 }
修正ありがとうございます！
問題ないこと確認できました

2024-06-08 09:58 UTC, Aki158 commented
@AkinoJoey さん

> 色々調査して試してみましたが、やはりカード情報の自動入力は無理そうでした！

調査ありがとうございます！
提案ですが、アカウント情報ページに以下のような、カード情報を表示するのはどうでしょうか?

### イメージ
![image](https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/assets/119317071/b0b66311-248c-4407-a356-e31d1be56e9b)

### 対象箇所

- src/app/views/customer/accounts/edit.html.erb
- src/app/views/customer/accounts/show.html.erb

#### 変更前
```
                <p class="text-base text-gray-500 md:text-lg">
                    デモサイトのため、金銭のやり取りは発生しません。<br />
                    商品ご購入時に、テスト用のカードデータをご用意致します。
                </p>
```

#### 変更後
```
                <p class="text-base text-gray-500 md:text-lg">
                    デモサイトのため、金銭のやり取りは発生しません。<br />
                    商品ご購入時には、以下のカード情報を手動で入力してください。
                </p>
                <div>
                    <p>カード番号</p>
                    <p class="w-full rounded border border-gray-300 p-2">
                        4242 4242 4242 4242
                    </p>
                </div>
                <div>
                    <p>有効期限(有効な将来の日付)</p>
                    <p class="w-full rounded border border-gray-300 p-2">
                        12/34
                    </p>
                </div>
                <div>
                    <p>セキュリティーコード(任意の3桁)</p>
                    <p class="w-full rounded border border-gray-300 p-2">
                        123
                    </p>
                </div>
```

2024-06-08 10:31 UTC, AkinoJoey commented
@Aki158 
良い案だと思います！
早速テスト用のカード情報を追加しました！

2024-06-08 10:55 UTC, Aki158 approved these changes
実装ありがとうございます！
すべて確認できましたので、承認しました〜
マージしてもらって、問題ありません。
お疲れ様でした🙇

2024-06-08 11:02 UTC, merged