Feature/#58 search with tag
recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync pull request #81
Opened 2024-06-15 09:48 UTC by AkinoJoey

## 概要

- 商品詳細ページにタグの表示
- タグを押すと、そのタグが付いている商品一覧が表示される

### Issue
https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/issues/58

## 目的
ユーザーがタグから商品を探せるようにするため

## やったこと
- 商品詳細ページにタグを表示
- タグを押すとそのタグが付いている商品一覧が表示される

## 確認方法

- https://art-sa2.com/admin/products で商品を選んでタグをつける
- タグをつけた商品の詳細画面ページを開く
- タグがついているか確認する
- タグを押してその商品が商品一覧ページに表示されるか確認する

## レビューで見てほしいこと、不安に思っていること

- 商品詳細ページにタグが表示されるかどうか
- タグを押すと、そのタグが付いている商品一覧が表示されるかどうか

2024-06-17 09:14 UTC, Aki158 requested changes
実装ありがとうございます！
タグに関わる機能が問題ないこと確認できました。
レビューコメントを書いたので、対応お願いします。

## レビュー
### 1. タグの商品一覧が表示されなくなる
以下の手順を実施すると、タグの商品一覧が表示されなくなります。
並び替えも利用できるように修正したほうが良いと思いました。

1. タグを押す
2. そのタグが付いている商品一覧が表示される
3. 並び替えを変更する(高評価順→高価格順)

### 2. タグの商品一覧かわからない
確認方法の手順を実施すると、タグの商品一覧が表示されますが、そのタグが付いた商品一覧かパッと見てわかりませんでした。商品一覧の商品にタグを表示するなどしたほうが良い気がしました。

2024-06-18 08:51 UTC, AkinoJoey commented
@Aki158 
[このイシュー](https://github.com/activerecord-hackery/ransack/issues/1393)と全く同じ状況になってしまい、ransackとActs-as-taggable-onの紐づけがうまくいかないため、product_categoryと同様の方法で組み込むのが難しい状況です（以下のようになります）
```ruby
irb(main):001> Product.ransack(tags_name_cont: '人気').result.to_sql
=> "SELECT `products`.* FROM `products`"
```

以下のような選択肢などがあると思いますが、どのような方法が良いと思いますか？
- タグの商品一覧はsearch_productコントローラーとは別で管理して、並び替え機能は実装しない
-  タグの商品一覧はsearch_productコントローラーとは別で管理して、並び替え機能はsearch_productコントローラーとは別のロジックとして実装する
- タグの商品一覧はsearch_productコントローラーで管理しつつ、search_products/index.html.erb の並び替え機能のみ別のロジックを考えて作成する

2024-06-18 13:40 UTC, Aki158 commented
@AkinoJoey さん
>このイシューと全く同じ状況になってしまい、ransackとActs-as-taggable-onの紐づけがうまくいかないため、product_categoryと同様の方法で組み込むのが難しい状況です（以下のようになります）

提案してもらった選択肢が、どれも複雑な実装になりそうな気がしたので、僕の方で実装してみました。
貼り付けてもらったイッシュー試したのですが、できなくて苦戦しました。。。笑
以下変更を適用させてローカル環境で動作を確認してみてください。
僕の環境で、期待通り動いてたので、大丈夫なはずです！

- src/app/controller/customer/search_products_controller.rb
```diff
-    @products = if params[:tag]
-                  Product.tagged_with(params[:tag])
-                else
-                  @keyword.blank? ? Product.all : @search.result(distinct: true)
-                end
+    @products = @search.result(distinct: true)
```

- src/app/models/product.rb
```diff
-  # Ransackで検索可能な関連付けを指定するメソッド
-  def self.ransackable_associations(_auth_object = nil)
-    ['product_category']
-  end
+  # Ransackで検索可能な関連付けを指定するメソッド
+  def self.ransackable_associations(_auth_object = nil)
+    %w[product_category taggings tags]
+  end
```

- src/app/views/customer/products/show.html.erb
```diff
-                    <% @product.tags.each do |tag|%>
-                        <%= link_to tag.name, search_products_path(tag: tag.name), class: 'bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300' %>
-                    <% end %>
+                    <% @product.tags.each do |tag|%>
+                        <%= link_to tag.name, search_products_path(q: { tags_name_eq: tag.name }), data: { turbo_method: :get }, class: 'bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300' %>
+                    <% end %>
```

- src/app/views/customer/search_products/index.html.erb
```diff
-            <%= search_form_for @search, url: search_products_path, method: :post, local: true, data: { turbo: false }, class: "flex max-w-sm items-center" do |form| %>
-                <% if @search.name_or_description_or_creator_or_product_category_name_cont.present? %>
-                    <%= form.hidden_field :name_or_description_or_creator_or_product_category_name_cont, value: @search.name_or_description_or_creator_or_product_category_name_cont %>
-                <% elsif @search.product_category_name_eq.present? %>
-                    <%= form.hidden_field :product_category_name_eq, value: @search.product_category_name_eq %>
-                <% end %>
-                <%= form.label :sorts, "並び替え :", class: "ml-1 block text-lg text-gray-900" %>
+            <%= search_form_for @search, url: search_products_path, method: :post, local: true, data: { turbo: false }, class: "flex max-w-sm items-center" do |form| %>
+                <% if @search.name_or_description_or_creator_or_product_category_name_cont.present? %>
+                    <%= form.hidden_field :name_or_description_or_creator_or_product_category_name_cont, value: @search.name_or_description_or_creator_or_product_category_name_cont %>
+                <% elsif @search.product_category_name_eq.present? %>
+                    <%= form.hidden_field :product_category_name_eq, value: @search.product_category_name_eq %>
+                <% end %>
+
+                <% if @search.tags_name_eq.present? %>
+                    <%= form.hidden_field :tags_name_eq, value: @search.tags_name_eq %>
+                <% end %>
+
+                <%= form.label :sorts, "並び替え :", class: "ml-1 block text-lg text-gray-900" %>
```

- src/config/initializers/acts_as_taggable_on_ransack.rb
```ruby
# ActsAsTaggableOnライブラリのTagクラスの拡張(Ransack用の設定追加)
ActsAsTaggableOn::Tag.class_eval do
  def self.ransackable_associations(_auth_object = nil)
    %w[taggings]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end
end
```

2024-06-19 01:31 UTC, AkinoJoey commented
@Aki158 
実装ありがとうございます！！
僕も色々試したのですが、以下のような書き方にする必要があったんですね、、、　勉強になります！！
非常に助かりました！

「2. タグの商品一覧かわからない」の部分も修正した（検索結果： 人気　みたいな感じで表示されるようにしました）のでご確認お願い致します！

```ruby
# ActsAsTaggableOnライブラリのTagクラスの拡張(Ransack用の設定追加)
ActsAsTaggableOn::Tag.class_eval do
  def self.ransackable_associations(_auth_object = nil)
    %w[taggings]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name]
  end
end
```

2024-06-19 04:14 UTC, Aki158 approved these changes
@AkinoJoey さん

実装ありがとうございます！
期待してた挙動に修正されていること確認できました。
承認しておきました。

1点、mergeミスの影響でページネーションに関わるエラーが出たので、修正してからプルリク閉じて欲しいです。

- src/app/controllers/customer/search_products_controller.rb
```diff
- @products = @search.result(distinct: true)
+ @products = @search.result(distinct: true).page(params[:page])
```

2024-06-19 11:17 UTC, seiichikick0404 commented
遅くなりすみません🙇‍♂️
以下の挙動確認できました。
承認させて頂きます！

- 詳細ページにタグの表示
- タグの一覧検索
- タグ一覧 -> フィルタリング

2024-06-19 11:18 UTC, seiichikick0404 approved these changes

2024-06-20 03:12 UTC, merged